const icons = {
  concept: {
    annulation: "fa-reply",
    annulationTotale: "fa-reply-all",
    associe: "fa-handshake",
    associes: "fa-users",
    capital: "fa-chart-line",
    conformite: "fa-award",
    exercices: "far fa-calendar-alt",
    mouvement: "fa-exchange-alt",
    per_mor: "fa-university",
    per_phy: "fa-user",
    regulation: "fa-euro-sign",
    repartition: "fa-chart-pie",
    societe: "fa-gavel",
    souscription: "fa-cart-arrow-down",
    forbidden: "fa-ban",
    documents: "fa-file",
    folder: "fa-folder",
    personalInfos: "fa-id-card",
    settings: "fa-cogs",
    squareCheck: "far fa-check-circle",
    squareCheckWait: "far fa-circle",
    key: "fa-key",
    down_arrow: "fas fa-caret-down"
  },
  action: {
    add: "add",
    backward: "fa-backward",
    close: "fa-close",
    compute: "fa-cogs",
    create: "fa-start",
    delete: "fa-trash-alt",
    detail: "fa-file-alt",
    doubleSuccess: "fa-check-double",
    download: "fa-download",
    upload: "fa-upload",
    edit: "fa-edit",
    error: "fa-exclamation-circle",
    forward: "fa-forward",
    help: "fa-question",
    home: "fa-home",
    info: "fa-info-circle",
    link: "fa-external-link-alt",
    menu: "fa-ellipsis-v",
    option: "fa-cog",
    print: "fa-print",
    remove: "fa-minus",
    save: "fa-save",
    search: "fa-search",
    share: "fa-share-alt",
    success: "fa-check",
    view: "fa-eye",
    sign_out: "fa-sign-out-alt",
    warning: "fa-exclamation-triangle",
    downloadPersonalFile: "fa-book",
    expand: "fa-search-plus"
  }
};

export default icons;
